import { db } from "./index";
import { students } from "./schema";

async function seed() {
    try {
        const students_data = [
            {
                section: "B",
                standing: 2,
                student_number: "23-050645",
                last_name: "Deimos",
                first_name: "Roger",
                middle_name: "Tabia",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050572",
                last_name: "Alvarez",
                first_name: "Lindberg Josh",
                middle_name: "Tacazon",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050588",
                last_name: "Tumamao",
                first_name: "Jeremy",
                middle_name: "Gumayagay",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050587",
                last_name: "Domingo",
                first_name: "Jann Dheyv",
                middle_name: "Agraan",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050573",
                last_name: "Aganus",
                first_name: "Gian Kenneth",
                middle_name: "Badanguio",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050562",
                last_name: "Ortal",
                first_name: "John Raphael",
                middle_name: "Pambid",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050662",
                last_name: "Cabugon",
                first_name: "Vincent Louise",
                middle_name: "Eclarin",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050615",
                last_name: "Hombrebueno",
                first_name: "Arlyn Grace",
                middle_name: "Pasibe",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050614",
                last_name: "Jallorina",
                first_name: "Lord Gian Cedric",
                middle_name: "Legaspi",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050610",
                last_name: "Costales",
                first_name: "Raven Althea",
                middle_name: "Rosales",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050580",
                last_name: "Asuncion",
                first_name: "Milben John",
                middle_name: "Garcia",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050568",
                last_name: "Barut",
                first_name: "Zenon Angelo",
                middle_name: "Reyes",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050627",
                last_name: "Panghulan",
                first_name: "Adrian",
                middle_name: "Lucena",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050575",
                last_name: "Bihasa",
                first_name: "John Rafael",
                middle_name: "Luna",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050593",
                last_name: "Salvador",
                first_name: "Van Justine",
                middle_name: "Dela Cruz",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050622",
                last_name: "Hilario",
                first_name: "Aaron Jade",
                middle_name: "Cudanes",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050616",
                last_name: "Garcia",
                first_name: "Glyza",
                middle_name: "Aurellano",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050612",
                last_name: "Asuncion",
                first_name: "Rzayne Jade",
                middle_name: "Dones",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050632",
                last_name: "Valdez",
                first_name: "Carl Vincent",
                middle_name: "Abuy",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050617",
                last_name: "Tolentino",
                first_name: "Abegail",
                middle_name: "Bautista",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050618",
                last_name: "Aoalin",
                first_name: "Nicole Anne",
                middle_name: "Panganiban",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050561",
                last_name: "Rabang",
                first_name: "Isaiah Timothy",
                middle_name: "Palapala",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050604",
                last_name: "Guillermo",
                first_name: "Jericho",
                middle_name: "Guerrero",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050619",
                last_name: "Tabila",
                first_name: "Sharwin Macario",
                middle_name: "Gabriel",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050006",
                last_name: "MANGAOIL",
                first_name: "KURT CHASSY",
                middle_name: "ALFEREZ",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050626",
                last_name: "Udaundo",
                first_name: "Jerlyn",
                middle_name: "Ulidan",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050584",
                last_name: "Espiritu",
                first_name: "John Rich",
                middle_name: "Pastor",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050566",
                last_name: "Muñoz",
                first_name: "Uriel Eyvind",
                middle_name: "Guittap",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050613",
                last_name: "Lacuesta",
                first_name: "Jhune Michael",
                middle_name: "Ramirez",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050611",
                last_name: "Viernes",
                first_name: "Jansen Jay",
                middle_name: "Mamuad",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050565",
                last_name: "ANCHETA",
                first_name: "MARK NEIL",
                middle_name: "PASCUAL",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050577",
                last_name: "Moises",
                first_name: "Aaron James",
                middle_name: "Edrada",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050624",
                last_name: "Dada",
                first_name: "Vanessa",
                middle_name: "Ordillos",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050567",
                last_name: "Delos Santos",
                first_name: "John Chrisley",
                middle_name: "Espiritu",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050689",
                last_name: "GUERRERO",
                first_name: "RED AXELL",
                middle_name: "DE GUZMAN",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050664",
                last_name: "Bingayen",
                first_name: "Norien",
                middle_name: "Ogot",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050633",
                last_name: "Gaoiran",
                first_name: "McJanielle",
                middle_name: "Dumlao",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050175",
                last_name: "Catubay",
                first_name: "Renz Jericho",
                middle_name: "Torralba",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050581",
                last_name: "Austria",
                first_name: "Edlyn Althea",
                middle_name: "Adriano",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050554",
                last_name: "Ventura",
                first_name: "Jhian Marco",
                middle_name: "Simbre",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050621",
                last_name: "Rabanal",
                first_name: "Mack Ryan",
                middle_name: "Virtud",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050563",
                last_name: "Agustin",
                first_name: "Karl Alexis",
                middle_name: "Delos Santos",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050594",
                last_name: "CALUMAG",
                first_name: "LOVYMAR JUSTIN THEO",
                middle_name: "RAMOS",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050553",
                last_name: "Casipit",
                first_name: "Lloyd",
                middle_name: "Dipit",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050650",
                last_name: "Meneses",
                first_name: "Mark John",
                middle_name: "Palomer",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050646",
                last_name: "Austria",
                first_name: "Marc Johnler",
                middle_name: "Mamaclay",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050590",
                last_name: "Ramos",
                first_name: "Kevin John",
                middle_name: "Santos",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050630",
                last_name: "BOADO",
                first_name: "ALLY BERT",
                middle_name: "DOMINGO",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050636",
                last_name: "Guiang",
                first_name: "Shannel Azeneth",
                middle_name: "Andres",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050586",
                last_name: "Ganitano",
                first_name: "Arvin Dave",
                middle_name: "Salvador",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050661",
                last_name: "Alisangco",
                first_name: "Reiley Angelo",
                middle_name: null,
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050582",
                last_name: "Lazo",
                first_name: "Carl Ashley",
                middle_name: "Bolivar",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050520",
                last_name: "Franco",
                first_name: "Kevin",
                middle_name: "Sagsagat",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050643",
                last_name: "Reyes",
                first_name: "Ian",
                middle_name: "Natividad",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050642",
                last_name: "Alcaraz",
                first_name: "Ralph Alvic",
                middle_name: "Semana",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050638",
                last_name: "Gappi",
                first_name: "Jacquelyn",
                middle_name: "Rafal",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050663",
                last_name: "Baraoed",
                first_name: "Aguiluz",
                middle_name: "Tagatac",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050599",
                last_name: "Ramos",
                first_name: "April Joy",
                middle_name: "Ravilas",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050685",
                last_name: "Nalupta",
                first_name: "John Carlo",
                middle_name: "Rico",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050628",
                last_name: "Bayangos",
                first_name: "Erich Lyka",
                middle_name: "Vila",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "A",
                standing: 2,
                student_number: "23-050623",
                last_name: "Tad-o",
                first_name: "Voltaire",
                middle_name: "Ansong",
                year_level: 2,
                year_admitted: 0,
            },
            {
                section: "B",
                standing: 2,
                student_number: "23-050637",
                last_name: "Edu",
                first_name: "Jhunro",
                middle_name: "Anapio",
                year_level: 2,
                year_admitted: 0,
            },
        ];
        await db.insert(students).values(students_data);
        console.log("✅ Students seeded successfully!");
    } catch (error) {
        console.error("❌ Seeding failed:", error);
    }
}

seed();
